/*
Print the max sum of possible subarrays of an array.
Applying brute force approach -- 2 nested loops.
O(n^3)
*/

#include <iostream>
using namespace std;
int main() {
    int n,ar[100],maxSum=0,currSum,left,right;
    cin>>n;
    for(int i=0;i<n;i++){
        cin>>ar[i];
    }

    for(int i=0;i<n;i++){
        for(int j=i;j<n;j++){
            currSum=0;
            for(int k=i;k<=j;k++){
                currSum += ar[k];

                if(currSum > maxSum){
                    maxSum = currSum;
                    left = i;
                    right = j;
                }       
            }
        }
    }

    cout<<"Max sum is : "<<maxSum<<endl;
    cout<<"Generated by subarray : ";
    for(int i=left;i<=right;i++){
        cout<<ar[i]<<" ";
    }
    return 0;
}
